# Generated by Django 4.1.3 on 2022-11-30 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_vendido_compradoel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendido',
            name='compradoEl',
            field=models.DateField(default=datetime.datetime(2022, 11, 30, 21, 11, 9, 649468)),
        ),
    ]
